// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MaximiseOrUnmaximiseWindow() {
  return window['go']['topmenu']['TopMenu']['MaximiseOrUnmaximiseWindow']();
}

export function MinimiseWindow() {
  return window['go']['topmenu']['TopMenu']['MinimiseWindow']();
}

export function QuitApp() {
  return window['go']['topmenu']['TopMenu']['QuitApp']();
}

export function SetContext(arg1) {
  return window['go']['topmenu']['TopMenu']['SetContext'](arg1);
}
