// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function AddGame(arg1:repository.AddGameParams):Promise<repository.Game>;

export function GetOneGame(arg1:number):Promise<repository.Game>;

export function ListGames():Promise<Array<repository.Game>>;
