// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Game struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Iconpath sql.NullString `json:"iconpath"`
}
