// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

type Game struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Iconpath string `json:"iconpath"`
}
