// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {node} from '../models';
import {graph} from '../models';

export function CreateFile(arg1:string):Promise<node.Node>;

export function DeleteFile(arg1:string):Promise<void>;

export function DuplicateFile(arg1:string,arg2:string):Promise<string>;

export function GetLabPath():Promise<string>;

export function GetRecentlyOpenedFiles():Promise<Array<string>>;

export function GetSubDirAndFiles(arg1:string):Promise<Array<node.Node>>;

export function MoveFileToExistingDir(arg1:string,arg2:string):Promise<string>;

export function OpenFile(arg1:string):Promise<graph.Graph>;

export function OpenMedia(arg1:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveFile(arg1:string,arg2:graph.Graph):Promise<void>;

export function SaveMedia(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
