// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1) {
  return window['go']['file_handler']['FileHandler']['CreateFile'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['file_handler']['FileHandler']['DeleteFile'](arg1);
}

export function DuplicateFile(arg1, arg2) {
  return window['go']['file_handler']['FileHandler']['DuplicateFile'](arg1, arg2);
}

export function GetLabPath() {
  return window['go']['file_handler']['FileHandler']['GetLabPath']();
}

export function GetRecentlyOpenedFiles() {
  return window['go']['file_handler']['FileHandler']['GetRecentlyOpenedFiles']();
}

export function GetSubDirAndFiles(arg1) {
  return window['go']['file_handler']['FileHandler']['GetSubDirAndFiles'](arg1);
}

export function MoveFileToExistingDir(arg1, arg2) {
  return window['go']['file_handler']['FileHandler']['MoveFileToExistingDir'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['file_handler']['FileHandler']['OpenFile'](arg1);
}

export function OpenMedia(arg1) {
  return window['go']['file_handler']['FileHandler']['OpenMedia'](arg1);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['file_handler']['FileHandler']['RenameFile'](arg1, arg2, arg3);
}

export function SaveFile(arg1, arg2) {
  return window['go']['file_handler']['FileHandler']['SaveFile'](arg1, arg2);
}

export function SaveMedia(arg1, arg2, arg3, arg4) {
  return window['go']['file_handler']['FileHandler']['SaveMedia'](arg1, arg2, arg3, arg4);
}
