// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileTree() {
  return window['go']['filetree']['FileTreeExplorer']['GetFileTree']();
}

export function SetConfigFile(arg1) {
  return window['go']['filetree']['FileTreeExplorer']['SetConfigFile'](arg1);
}

export function SetContext(arg1) {
  return window['go']['filetree']['FileTreeExplorer']['SetContext'](arg1);
}
