// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewFile(arg1) {
  return window['go']['filetree']['FileTreeExplorer']['CreateNewFile'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['filetree']['FileTreeExplorer']['DeleteFile'](arg1);
}

export function GetFirstDepth() {
  return window['go']['filetree']['FileTreeExplorer']['GetFirstDepth']();
}

export function GetLabPath() {
  return window['go']['filetree']['FileTreeExplorer']['GetLabPath']();
}

export function GetTheWholeTree() {
  return window['go']['filetree']['FileTreeExplorer']['GetTheWholeTree']();
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['filetree']['FileTreeExplorer']['RenameFile'](arg1, arg2, arg3);
}
