// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1) {
  return window['go']['filetree']['FileTree']['CreateFile'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['filetree']['FileTree']['DeleteFile'](arg1);
}

export function DuplicateFile(arg1, arg2) {
  return window['go']['filetree']['FileTree']['DuplicateFile'](arg1, arg2);
}

export function GetDirectories() {
  return window['go']['filetree']['FileTree']['GetDirectories']();
}

export function GetLabDirs() {
  return window['go']['filetree']['FileTree']['GetLabDirs']();
}

export function GetLabPath() {
  return window['go']['filetree']['FileTree']['GetLabPath']();
}

export function GetRecentlyOpenedFiles() {
  return window['go']['filetree']['FileTree']['GetRecentlyOpenedFiles']();
}

export function GetSubDirAndFiles(arg1) {
  return window['go']['filetree']['FileTree']['GetSubDirAndFiles'](arg1);
}

export function MoveFileToExistingDir(arg1, arg2) {
  return window['go']['filetree']['FileTree']['MoveFileToExistingDir'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['filetree']['FileTree']['OpenFile'](arg1);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['filetree']['FileTree']['RenameFile'](arg1, arg2, arg3);
}

export function SaveFile(arg1, arg2) {
  return window['go']['filetree']['FileTree']['SaveFile'](arg1, arg2);
}
