// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewFileAtRoot(arg1) {
  return window['go']['filetree']['FileTreeExplorer']['CreateNewFileAtRoot'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['filetree']['FileTreeExplorer']['DeleteFile'](arg1);
}

export function DuplicateFile(arg1, arg2) {
  return window['go']['filetree']['FileTreeExplorer']['DuplicateFile'](arg1, arg2);
}

export function GetDirectories() {
  return window['go']['filetree']['FileTreeExplorer']['GetDirectories']();
}

export function GetLabDirs() {
  return window['go']['filetree']['FileTreeExplorer']['GetLabDirs']();
}

export function GetLabPath() {
  return window['go']['filetree']['FileTreeExplorer']['GetLabPath']();
}

export function GetSubDirAndFiles(arg1) {
  return window['go']['filetree']['FileTreeExplorer']['GetSubDirAndFiles'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['filetree']['FileTreeExplorer']['MoveFile'](arg1, arg2);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['filetree']['FileTreeExplorer']['RenameFile'](arg1, arg2, arg3);
}

export function SaveFile() {
  return window['go']['filetree']['FileTreeExplorer']['SaveFile']();
}
