// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectories():Promise<Array<string>>;

export function GetLabDirs():Promise<void>;

export function GetLabPath():Promise<string>;
