// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1) {
  return window['go']['dirhandler']['DirHandler']['CreateDirectory'](arg1);
}

export function DeleteDirectory(arg1) {
  return window['go']['dirhandler']['DirHandler']['DeleteDirectory'](arg1);
}

export function GetDirectories() {
  return window['go']['dirhandler']['DirHandler']['GetDirectories']();
}

export function GetLabDirs() {
  return window['go']['dirhandler']['DirHandler']['GetLabDirs']();
}

export function GetLabPath() {
  return window['go']['dirhandler']['DirHandler']['GetLabPath']();
}

export function MoveDir(arg1, arg2) {
  return window['go']['dirhandler']['DirHandler']['MoveDir'](arg1, arg2);
}

export function RenameDirectory(arg1, arg2) {
  return window['go']['dirhandler']['DirHandler']['RenameDirectory'](arg1, arg2);
}
