// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectories() {
  return window['go']['dirhandler']['DirHandler']['GetDirectories']();
}

export function GetLabDirs() {
  return window['go']['dirhandler']['DirHandler']['GetLabDirs']();
}

export function GetLabPath() {
  return window['go']['dirhandler']['DirHandler']['GetLabPath']();
}
