// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {node} from '../models';

export function CreateDirectory(arg1:string):Promise<node.Node>;

export function DeleteDirectory(arg1:string):Promise<void>;

export function GetDirectories():Promise<Array<string>>;

export function GetLabDirs():Promise<void>;

export function GetLabPath():Promise<string>;

export function RenameDirectory(arg1:string,arg2:string):Promise<void>;
