// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConfigPresence() {
  return window['go']['config']['AppConfig']['CheckConfigPresence']();
}

export function CreateAppConfig(arg1) {
  return window['go']['config']['AppConfig']['CreateAppConfig'](arg1);
}

export function GetConfigFile() {
  return window['go']['config']['AppConfig']['GetConfigFile']();
}

export function LoadConfigFileInMemory() {
  return window['go']['config']['AppConfig']['LoadConfigFileInMemory']();
}

export function OpenCreateLabDialog() {
  return window['go']['config']['AppConfig']['OpenCreateLabDialog']();
}

export function SetConfigFile(arg1) {
  return window['go']['config']['AppConfig']['SetConfigFile'](arg1);
}

export function SetContext(arg1) {
  return window['go']['config']['AppConfig']['SetContext'](arg1);
}
