// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function CheckConfigPresence():Promise<boolean>;

export function CreateAppConfig(arg1:string):Promise<void>;

export function GetConfigFile():Promise<config.ConfigFile>;

export function LoadConfigFileInMemory():Promise<void>;

export function OpenCreateLabDialog():Promise<string>;

export function SetConfigFile(arg1:config.ConfigFile):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
