// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1) {
  return window['go']['recent']['RecentlyOpened']['AddRecentFile'](arg1);
}

export function GetLabPath() {
  return window['go']['recent']['RecentlyOpened']['GetLabPath']();
}

export function GetRecentlyOpenedFiles() {
  return window['go']['recent']['RecentlyOpened']['GetRecentlyOpenedFiles']();
}

export function SaveRecentlyOpended() {
  return window['go']['recent']['RecentlyOpened']['SaveRecentlyOpended']();
}
