// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1:string):Promise<void>;

export function GetLabPath():Promise<string>;

export function GetRecentlyOpenedFiles():Promise<Array<string>>;

export function SaveRecentlyOpended():Promise<void>;
